require_relative "../app/advent.rb"
require_relative "../app/day_7.rb"

RSpec.describe(Day_7) do
  subject(:day) { described_class.new }

  before do
    example = <<~EOF
      .......S.......
      ...............
      .......^.......
      ...............
      ......^.^......
      ...............
      .....^.^.^.....
      ...............
      ....^.^...^....
      ...............
      ...^.^...^.^...
      ...............
      ..^...^.....^..
      ...............
      .^.^.^.^.^...^.
      ...............
    EOF

    allow(File).to receive(:readlines).and_return(example.split(/\n/))
  end

  it 'part 1 returns 21' do
    expect(day.part_1).to eq(21)
  end

  it 'part 2 returns 40' do
    expect(day.part_2).to eq(40)
  end
end
